#+TITLE: 番茄工作法
#+DATE: 2016-03-06
#+SETUPFILE: ~/work/Dropbox/octopress/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 政經管法
#+JEKYLL_TAGS: 個人管理 番茄工作法 時間管理
#+JEKYLL_PUBLISHED: true
#+JEKYLL_COMMENTS: true

『只擡頭仰望山峰，而不腳踏實地的去攀爬，我們永遠都不會到達山頂，也永遠不會有「會
當凌絕頂，一覽眾山小」的感覺』

每年的年初，我們都會給自己設定目標、安排計劃。我們都會和自己說：『新的一年，我一
定會完成今年的目標的』。可是，每到年底，我們又常常抱怨時間過的太快了，然後又寄希望
於下一個新年。不斷如此的往復，不但完不成我們的設定的目標，更會磨掉我們意志，最終
一事無成。那麼，如何才能克服這些呢？有沒有簡單易學，效果好的方法呢？

{{{more}}}

我也是一箇中度拖延症患者，在 2015 年參加註冊會計師的考試中，最終以較滿意的成績通
過了大部分的科目。總結考試的成功，我想更多的是因為那段時間奉行「一次只做一件事」
的哲學，沒有將有限的精力分散，從而獲得了較好的成績。從考試結束到現在將近一個季度
的時間，卻感覺想做的事情很多，但都是半途而廢，毫無結果。從一些博客、書籍上了解到
了「番茄工作法」，靜下心來閱讀了幾本相關的書籍，決定親自實踐該時間管理方法。

番茄工作法由 Francesco Cirillo 創立，目的是讓人集中精力專注做一件事情，從而最終
達到把這件事做完、做好的目標。該方法能夠有效的培養起我們的專注力，並逐漸降低拖延
症的症狀。

* 前提基礎

番茄工作法的核心目標就是讓自己能夠做完並做好一件事情，推崇「一次只做一件事情」的
原則。該方法是建立在大腦工作機制、簡單易用原則的基礎上的。番茄工作法簡單，所以易
學、易用、易實踐。所需要的工具也比較少，主要有：
1. 番茄計時器〔家用廚房計時器〕
2. 工作計劃表〔To Do Today〕
   1. 小標題〔時間、地點、人物〕
   2. 清單，今日需完成的事情〔先後順序排列〕
   3. 計劃外的緊急事件〔中斷事件〕
3. 活動清單〔Activity Inventory〕
   1. 標題：人物、事件
   2. 隨想隨記
4. 紀錄表〔記錄原始數據、Excel〕

* 如何使用
番茄工作法就是全神貫注的工作 25 分鐘，在休息 3 ~ 5 分鐘，在全神貫注的工作 25 分
鍾，在休息 3 ~ 5 分鐘，如此循環往復。強迫自己一個番茄鍾之內只做一件事情。番茄工
作法主要分為下述五個階段。

** 計劃：計劃一天要做的事情

*** 列舉出代辦事項
每日清晨，我們都要羅列需要做的事情，並從中挑選出今日需要完成的事情，進行排序，最
後寫入到進行一天工作的計劃，把需要做的事情進行羅列，挑選出「今日事」，最後寫入到
「工作計劃表」中。主要有下述幾個步驟：
1. 羅列所需完成的事情。工作、學習、健身等方面的事情，都羅列出來。
2. 按照事情的重要性和緊急性〔參照《要事第一》〕對所有的事情進行排序，並從鍾挑選
   出「今日事」。
3. 將「今日事」寫入到「工作計劃表」中去。

*** 對每一個事項完成時長進行簡單預測
當「工作計劃表」的任務清單完成後，接下來就需要對完成該任務需要的番茄鍾數目進行預
測，並將預測的數目寫入到相應的欄目中。

在該步驟中，可能會出現下述問題：
1. 任務時間很難預測。每當碰到新任務或者複雜任務的事後，都會碰到這種情況，那麼，
   我們可以採取下述步驟進行相應的解決：
   1. 先安排幾個番茄鍾對該任務進行資料查閱等操作，方便後續的預測。
   2. 如果查閱資料後，還是不能預測整體完成時間，那麼先填上第一階段的部分，等完成
      該部分，在進行後續的預測。
2. 任務時間可以預測，但是過長或者過短。
   1. 如果過長（超過 8 個），那麼說明這個任務過於複雜，建議將該任務分解成更小的
      單位，最好能夠在四到五個番茄鍾之內完成。
   2. 如果完成該任務不需要一個番茄鍾，那麼說明任務過於簡單，可以將多個簡單的任務
      合併成一個任務，能夠充滿一個番茄鍾。記住：番茄鍾是一個最小的原子單位，不能
      出現半個、三分之一等番茄鍾。

|------+-------+----------+------+------------+------------|
| 開始 |  結束 | 內容詳情 | 類別 | 預測番茄數 | 實際番茄數 |
|------+-------+----------+------+------------+------------|
| 9:00 | 12:00 | 背單詞   | 學習 |          3 | * *        |
|------+-------+----------+------+------------+------------|

** 追蹤：邊工作邊記錄
該步驟是番茄工作法的核心內容，也是其他時間管理方法幾乎都忽略的部分，該步驟是讓自
己「一次只做一件事情」、保持專注力、把一件事情做完且做好的重要實踐步驟。

*** 基本做法
1. 將番茄鐘調整到 25 分鐘，進行倒計時，這段期間全神貫注的工作、學習等。
2. 當鈴聲響起（25 分鐘結束），休息 3 ~ 5 分鐘。
3. 休息結束之後，在重複第一步驟，繼續工作 25 分鐘，結束後，在休息 3 ~ 5 分鐘。
4. 如此重複 3 ~ 4 輪之後，休息 15 ~ 30 分鐘。

*** 任務提前完成
一般情況下，就算任務提前完成了，還需要繼續進行工作，不到鈴聲響起，不能休息的。如
果說任務在 5 分鐘內完成，而且該任務本應該在上個番茄鍾內完成的，就繼續下一個任務。
一般其他情況下，比較建議回顧一下剛剛完成的任務，進行相應的總結或者歸納，讓知識點
掌握的更加牢靠。記住：不到鈴聲響起，除非特別緊急的事情，我們不能中斷番茄鍾

*** 如何處理中斷
即使是短短 25 分鐘的時間，我們也經常會被中斷。中斷的來源主要分為內部中斷和外部中
斷，內部中斷主要來源於自身額外的想法、靈光一現等，外部中斷主要來源於電子郵件、手
機、同事等的打擾。如何處理以及處理的好壞，直接關注到番茄工作法的效率。

**** 內部中斷：來源於自身的中斷
在一般的工作中，一旦發生自身的中斷，我們經常會放下手中的工作，去做這些事情。比如
說，我們突然餓了，可能就會去訂餐、吃飯；突然想起一個本應該打的電話，可能就回去電
話聊天了。相應的，時間也就流逝了。如何處理這些內部中斷呢？主要分為下面幾個核心點：
1. 讓內部中斷變得明顯。一旦有內部中斷這種意識，立馬寫下來，然後在回到工作中去。
2. 將內部中斷記錄在「意外緊急事件」，等該番茄鍾完成後在進行相關的處理。

**** 外部中斷：來源於他人的中斷
外部中斷一般來源於同事、郵件、信息、電話的打擾。下面根據中斷來源的不同，
提供相應的解決方法。
- 郵件、信息 :: 將郵件、信息這些調成靜音，不要讓自己在番茄鍾內聽到這些提醒信息，
     就可以較好的避免該類中斷。
- 同事、電話 :: 同事、或者電話的中斷，可以根據該中斷不重要，比如說同事事情不緊急，
     電話是騷擾電話等，這種情況就將這些事情推遲，並寫入到「意外緊急事件」中。如
     果說該中斷很重要，立馬放棄當前的番茄鍾，解決當前中斷，下次重新開始一個新的
     番茄鍾，就算是還有 5 分鐘結束該番茄鍾了。

** 記錄：整理一天的工作檔案
每天結束之後，都需要將今天記錄所做的事情整理成文檔，方便後續的分析以及以後的翻閱。
在該步驟中，我們需要以下幾個字段：
1. 日期
2. 任務描述和類型（方便後續統計在各個類別上花的時間）
3. 預測番茄數和實際使用番茄數，並記錄差異。

|-------+-------+----------+------+------------+------------+------|
|  開始 |  結束 | 內容詳情 | 類別 | 預測番茄數 | 實際番茄數 | 差異 |
|-------+-------+----------+------+------------+------------+------|
|  9:00 | 12:00 | 背單詞   | 學習 |          3 |          2 |    1 |
| 13:00 | 15:00 | 寫代碼   | 工作 |          4 |          5 |   -1 |
|-------+-------+----------+------+------------+------------+------|

** 分析：分析一天的收穫、進展
每天完成工作記錄完成之後，就需要對今日工作進行分析和總結。主要應該回答
下述問題：
1. 今日是否完成了相應的任務？
2. 如果完成了，那麼完成的質量如何？還有可以改進的空間嗎？
3. 如果沒有完成，是因為任務設定的過多呢？還是因為番茄鍾使用過程中的問題，比如一
   直無法集中精力，經常被中斷或者遇到緊急的事情。
4. 如果沒有完成，那麼沒完成的任務該怎麼處理，是不處理了還是接著明天的安排呢？
5. 每天又該如何提高自身預測番茄數的能力呢？

** 可視化：展示有用的信息，看到自身的進步
可視化主要將自身的進步展現出來，給自己不斷的激勵。每當年底的時候，看著自己一年的
工作、學習，希望能夠很開心的說：「哇，這種感覺真好」。

可視化是因人而異的，也是每個人對自己不同要求的體現。可視化最核心的目的是一定要看
到自身的進步和缺陷，不斷去彌補自身的缺陷，獲得更大的成長。下面是我比較推薦的一些
統計、可視化方向：
1. 統計每類工作的總番茄數目：學習、工作、修身、健身、娛樂
2. 展示自己一段時間取得的成績
   1. 在工作上面，完成了哪些任務，提升了哪些技能
   2. 在學習上，自身的精神、技能都獲得了哪些方面的成長
   3. 健身上面，體能提升的量化
   4. 修身方面，自己的人生觀、價值觀得到什麼成長
