#+TITLE: 我的人生
#+DATE: 2016-08-13
#+SETUPFILE: ~/work/Dropbox/octopress/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 文史哲
#+JEKYLL_TAGS: 自我介紹 人生目標
#+JEKYLL_PUBLISHED: true
#+JEKYLL_COMMENTS: true

這篇文章是在 2016 年 8 月 13 日在 toastermaster 南京第一中文俱樂部破冰演講的演講
稿，主要是闡述了自己的職業、興趣和自我實現三個層次的內容，下面是完整的演講稿。

大家好，我叫張榮，今天由我來做個自我介紹。人活著有很多的需求，美國心理學家馬斯洛
曾提出人類需求五層次理論，分別是生理、安全、社會、尊重和自我實現 。今天我想從
『如何活下來』，『如何活的開心』以及『如何實現自身價值』這三個層次來談談我的人生。

{{{more}}}

首先是如何活下來，現代社會分工越來越細，擁有一項專業的技能是生存的基本條件，對於
川大軟件工程畢業的我而言， 數據挖掘成了我一項專業技能，這是一門結合了統計學、編
程、機器學習等學科的綜合性領域 。除了專業技術之外，我還想提升溝通力，公眾演講力
和領導力，這是我加入頭馬的目的，但我相信這絕對不是我加入頭馬的唯一的收穫 。

人生不如意十之八九，活下來的人要面對生活的各種苦難，怎麼讓自己活得更加幸福呢？一
種解決方法是培養幾項能夠長期堅持的業餘愛好，那麼，對我而言，一是閱讀，二是瑜伽。

梁啟超曾說：『一個人如果不能養成主動閱讀的習慣，這個人，簡直是剝奪了自己的終身幸
福』。書籍是人類進步的階梯，而閱讀就是努力攀爬的過程，那麼閱讀給我帶來了什麼呢？

首先，閱讀讓我看到了各種各樣的人生，能夠讓我更加平靜的面對生活的各種不確定性。張
國榮曾說：『人說貓有九條命，而做演員可以超過九條命，因為每一個角色都是一個新的生
命』。每次我閱讀完一本小說的時候，我都會感慨到原來人還可以這樣活著，每當讀完一本
名人傳記，我都會對自己說：『你看，他們也曾那樣痛苦的掙扎過』。

其次，閱讀增長了我的智慧，文、史、哲、政、經、法，這些都是人類幾千年智慧的結晶，
除了閱讀，我想不到更好的方法去掌握這些祖先留給我們的智慧。

更為重要的是，閱讀是一場思維的訓練，是一次和名人間的對話 。查理·芒格傳授了我多元
化思維、逆向思維等。保羅·格雷厄姆則教會了我如何做到不隨波逐流，人云亦云，還有王
小波、陀思妥耶夫斯基、巴爾扎克等等。

如果說閱讀是大腦的一種修行，那麼瑜伽對我而言則是身心的修行。接觸瑜伽是一個非常偶
然的過程，我的同事拉著我去健身房諮詢，我發現瑜伽老師非常好看，於是我就嘗試著去上
一次瑜伽體驗課。那是一個星期五晚上，我懷著忐忑的心情去第一次走進瑜伽的教室，放眼
望去，不同年齡段的美女映入眼廉，但是卻沒有掃描到一個帥哥，我默默的問自己：『我是
不是選錯了方向，不管了，豁出去吧，反正就這一次』。隨著上課的不斷進行，隨著老師不
斷的做出拜日式、星月式、三角式等優美的體式，我也逐漸地融入到了這項運動中去。課程
結束後，老師對我說：『第一次來吧，練的還可以』。我大受鼓舞，隨著後續不斷深入的閱
讀和練習，認識到瑜伽不僅僅是女性的專項運動，除了柔軟，瑜伽更需要力量、平衡和控制，
這體現了它極其陽剛的一面。

談完了職業和興趣，接下來就是自我實現價值層次了，我一直在思考，我想成為什麼樣的人，
想擁有怎樣的人生，在不斷的思考中，我慢慢總結出一句話，我希望「在我人生的每個年齡
階段，具備該階段應有的智慧，以及能夠將這些智慧分享給周圍的人 」。

謝謝大家，希望大家能夠記住我，一個從事著現代社會最先進的職業，同時又練習著最
古老的東方運動。
